name: Workflow - Build and Deployment to Azure Environments

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  actions: read
  checks: write

env:
  ARTIFACT_NAME: "my-webapi-artifact"
  SOLUTION_NAME: "MyWebApi"
  SOLUTION_PATH: "src/MyWebApi/MyWebApi.sln"
  AZURE_SUBSCRIPTION_ID: "my-subscription-id"

jobs:
  Setup:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: ${{ env.ARTIFACT_NAME }}
      solution_name: ${{ env.SOLUTION_NAME }}
      solution_path: ${{ env.SOLUTION_PATH }}
      azure_subscription_id: ${{ env.AZURE_SUBSCRIPTION_ID }}
    steps:
      - name: Setting up environment variables
        run: echo "Setting up environment variables"

  Build-and-Test:
    name: Build, Test & Publish
    needs: Setup
    uses: ./.github/workflows/template-build-test-publish.yaml
    with:
      artifact_name: ${{ needs.Setup.outputs.artifact_name }}
      solution_name: ${{ needs.Setup.outputs.solution_name }}
      solution_path: ${{ needs.Setup.outputs.solution_path }}

  Deploy:
    name: Deploy to Environments
    if: github.event_name == 'push'
    needs: [Setup, Build-and-Test]
    strategy:
      matrix:
        environment:
          - name: DEV
            resource_group: "my-resource-group-dev"
            webapp_name: "my-app-dev"
            azure_subscription_id: "random-guid"
          - name: TEST
            resource_group: "my-resource-group-test"
            webapp_name: "my-app-test"
            azure_subscription_id: "random-guid"
          - name: PROD
            resource_group: "my-resource-group-prod"
            webapp_name: "my-app-prod"
            azure_subscription_id: "random-guid"
    uses: ./.github/workflows/template-deploy.yaml
    with:
      environment: ${{ matrix.environment.name }}
      subscription_id: ${{ matrix.environment.azure_subscription_id }}
      resource_group: ${{ matrix.environment.resource_group }}
      webapp_name: ${{ matrix.environment.webapp_name }}
      artifact_name: ${{ needs.Setup.outputs.artifact_name }}
    secrets: inherit